baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Cam Rodriguez'
theme = 'hugo-theme-console'

[params]
  description = "Cam Rodriguez's personal website"
  animateStyle = "animate-fade-up" # Animation style for content

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Resume"
  url = "/resume/"

[[params.navlinks]]
  name = "Posts"
  url = "/posts/"

[[params.navlinks]]
  name = "Photos"
  url = "/photos/"